Web_053505_Snetko/Entities/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web_053505_Snetko.Entities
{
    public class ApplicationUser : IdentityUser
    {
    }
}

Web_053505_Snetko/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web_053505_Snetko.Models
{
    public class Cart
    {
    }
}

Web_053505_Snetko/Models/ErrorViewModel.cs
using System;

namespace Web_053505_Snetko.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web_053505_Snetko/Models/MenuItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web_053505_Snetko.Models
{
    public class MenuItem
    {
        public bool IsPage { get; set; }
        public string Text { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Page { get; set; }
        public string Area { get; set; }
        public string Active { get; set; }
    }
}

Web_053505_Snetko/Components/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web_053505_Snetko.Models;

namespace Web_053505_Snetko.Components
{
    public class CartViewComponent :  ViewComponent
    {
        private Cart _cart;
        public CartViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

Web_053505_Snetko/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web_053505_Snetko.Models;

namespace Web_053505_Snetko.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private List<MenuItem> _menuItems = new List<MenuItem>()
        {
            new MenuItem {Controller = "Home", Action = "Index", Text = "Lab 2"},
            new MenuItem {Controller = "Product", Action = "Index", Text = "Каталог"},
            new MenuItem {IsPage = true, Area = "Admin", Page = "/Index", Text = "Администрирование"}
        };

        public IViewComponentResult Invoke()
        {
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];

            foreach (var item in _menuItems)
            {
                var _matchController = controller?.Equals(item.Controller) ?? false;
                var _matchArea = area?.Equals(item.Area) ?? false;

                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }

            return View(_menuItems);
        }

    }
}

Web_053505_Snetko/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web_053505_Snetko.Controllers
{
    public class HomeController : Controller
    {
        private List<ListDemo> _listDemo;

        public HomeController()
        {
            _listDemo = new List<ListDemo>
            {
            new ListDemo{ ListItemValue=1, ListItemText="Item 1"},
            new ListDemo{ ListItemValue=2, ListItemText="Item 2"},
            new ListDemo{ ListItemValue=3, ListItemText="Item 3"}
            };
        }

        public IActionResult Index()
        {
            ViewData["Text"] = "Лабораторная работа 2";
            ViewData["Lst"] = new SelectList(_listDemo, "ListItemValue", "ListItemText");
            return View();
        }
    }

    public class ListDemo
    {
        public int ListItemValue { get; set; }
        public string ListItemText { get; set; }
    }
}

Web_053505_Snetko/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная страница";
}
<h2>@ViewData["Text"]</h2>
<h3>Список</h3>
<ol type="A">
    @for (int i = 1; i < 5; i++)
    {
        <li>элемент @i списка</li>
    }
</ol>
<hr>
<h2>Форма</h2>
<select asp-items="@ViewData["Lst"] as SelectList"></select>
<form method="GET">
    <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="checkbox" id="gridCheck1" value="chk1">
                <label class="form-check-label" for="gridCheck1">
                    Чек-бокс 1
                </label>
                <br>
                <input class="form-check-input" type="checkbox" name="checkbox" id="gridCheck2" value="chk2">
                <label class="form-check-label" for="gridCheck2">
                    Чек-бокс 2
                </label>
            </div>
        </div>
    </div>
    <fieldset class="form-group">
        <div class="row">
            <div class="col-sm-10 offset-sm-2">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1"
                           value="option1" checked>
                    <label class="form-check-label" for="gridRadios1">
                        Радио-1
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2"
                           value="option2">
                    <label class="form-check-label" for="gridRadios2">
                        Радио-2
                    </label>
                </div>
                <div class="form-check disabled form-check-inline">
                    <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios3"
                           value="option3">
                    <label class="form-check-label" for="gridRadios3">
                        Радио-3
                    </label>
                </div>
            </div>
        </div>
    </fieldset>
    <div class="form-group row">
        <label for="inputEmail3" class="col-sm-2 col-form-label">Логин:</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" name="passName" id="inputEmail3" placeholder="Введите имя">
        </div>
    </div>
    <div class="form-group row">
        <label for="inputPassword3" class="col-sm-2 col-form-label">Пароль:</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" name="passPassword" id="inputPassword3" placeholder="Введите пароль">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </div>
</form>

Web_053505_Snetko/Views/Shared/Components/Menu/Default.cshtml
@model IEnumerable<MenuItem>

<div class="navbar-nav">
    @foreach (var item in Model)
    {
        @if (item.IsPage)
        {
            <a class="nav-item nav-link @item.Active" asp-area="@item.Area" asp-page="@item.Page">
                @item.Text
            </a>
        }
        else
        {
            <a class="nav-item nav-link @item.Active" asp-controller="@item.Controller" asp-action="@item.Action">
                @item.Text
            </a>
        }
    }
</div>

Web_053505_Snetko/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web_053505_Snetko</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <script src="lib/jquery/dist/jquery.js"></script>
    <script src="lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->
                <a class="navbar-brand" href="#">05350148</a>
                <div class="navbar-nav">
                    @await Component.InvokeAsync("Menu")
                </div>
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                <partial name="_UserPartial" />
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
        </div><!-- container - конец -->
    </header><!-- header - конец -->
    <main class="container">
        @RenderBody()
    </main>
    <footer>
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

<!--
<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web_053505_Snetko</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @*@RenderBody()*@
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Web_053505_Snetko - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
-->

Web_053505_Snetko/Views/Shared/_UserPartial.cshtml
@await Component.InvokeAsync("Cart")
<a asp-controller="Cart" asp-action="Index" class="navbar-text ml-auto">
    00,0 руб <i class="fas fa-shopping-cart nav-color"></i> (0)
</a>
<div class="dropdown ml-4 nav-color">
    <div class="dropdown-toggle" id="dropdownMenuButton"
         data-toggle="dropdown"
         aria-haspopup="true" aria-expanded="false">
        <img src="~/images/avatar.jpg" width="30" alt="User"
             class="rounded" />
    </div>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <div class="dropdown-item-text">
            <img src="~/images/avatar.jpg" width="50" alt="User"
                 class="rounded" />
            user@mail.ru
        </div>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" asp-controller="Product"
           asp-action="UserProducts">Мои товары</a>
        <a class="dropdown-item" asp-area="Identity"
           asp-page="/Account/Logout">Log off</a>
    </div>
</div>
<!--
<a asp-controller="Cart" asp-action="Index" class="navbar-text ml-auto">
    00,0 руб <i class="fas fa-shopping-cart nav-color"></i> (0)
</a>
<div class="dropdown ml-4 nav-color">
    <div class="dropdown-toggle" id="dropdownMenuButton"
         data-toggle="dropdown"
         aria-haspopup="true" aria-expanded="false">
        <img src="~/images/avatar.jpg" width="30" alt="User"
             class="rounded" />
    </div>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <div class="dropdown-item-text">
            <img src="~/images/avatar.jpg" width="50" alt="User"
                 class="rounded" />
            user@mail.ru
        </div>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" asp-controller="Product"
           asp-action="UserProducts">Мои товары</a>
        <a class="dropdown-item" asp-area="Identity"
           asp-page="/Account/Logout">Log off</a>
    </div>
</div>
-->